version: '3.3'
services:
  feishu-chatgpt:
    container_name: feishu-chatgpt
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9000:9000/tcp"
    # volumes:
    #   - ./code/config.yaml:/app/config.yaml:ro
    environment:
      APP_ID: cli_a495909c2db8d013
      APP_SECRET: RLam8pOsCNxxtc9SpYdDkfLm2FFEdCwb
      APP_ENCRYPT_KEY: 27iSf6GFC1TA5wo31ecwIgljwX1Xp6KZ
      APP_VERIFICATION_TOKEN: aXFD1HRXtigA4XkXyBcT4f8jkk52MGoj
      # 请确保和飞书应用管理平台中的设置一致
      BOT_NAME: chatGpt
      # OpenAI API Key 支持负载均衡, 可以填写多个 Key 用逗号分隔
      OPENAI_KEY: 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,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
      # 服务器配置
      HTTP_PORT: 9000
      HTTPS_PORT: 9000
      USE_HTTPS: false
      CERT_FILE: cert.pem
      KEY_FILE: key.pem
      # OpenAI 地址, 一般不需要修改, 除非你有自己的反向代理
      API_URL: https://api.openai.com
      # 代理设置, 例如 "http://127.0.0.1:7890", "" 代表不使用代理
      HTTP_PROXY: ""
